server:
  port: 8081

spring:
  application:
    name: EventService
  datasource:
    url: jdbc:postgresql://localhost:5432/eventservice
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  # Redis Configuration
  # Session Management with Redis
  session:
    store-type: redis
    redis:
      namespace: hotel:session
      flush-mode: on-save
    timeout: 3600  # Session timeout in seconds (1 hour)
  data:
    redis:
      host: redis
      port: 6379
      timeout: 2000