apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-auth-service
  template:
    metadata:
      labels:
        app: user-auth-service
    spec:
      containers:
      - name: user-auth-service
        image: hazemabdelghany/user-auth-service:latest
        ports:
        - containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: user-auth-service
spec:
  type: ClusterIP
  selector:
    app: user-auth-service
  ports:
  - port: 8085
    targetPort: 8085 