apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: microservices-app
type: Opaque
data:
  # Base64 encoded values
  MONGODB_URI: bW9uZ29kYjovL21vbmdvZGI6MjcwMTc=  # mongodb://mongodb:27017
  REDIS_URI: cmVkaXM6Ly9yZWRpczo2Mzc5  # redis://redis:6379
  RABBITMQ_URI: YW1xcDovL2d1ZXN0Omd1ZXN0QHJhYmJpdG1xOjU2NzI=  # amqp://guest:guest@rabbitmq:5672 