apiVersion: v1
kind: Service
metadata:
  name: booking-service
  namespace: microservices-app
spec:
  selector:
    app: booking-service
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: microservices-app
spec:
  selector:
    app: payment-service
  ports:
  - port: 3001
    targetPort: 3001
  type: ClusterIP 